---
layout: cv
title: Drew Howells' Resume
---
# Drew Howells

__Rexburg, ID | 720-254-8063 | [drewjhowells@gmail.com] | linkedin.com/in/drewhowells/__

Software Engineering student dedicated to improving skills through hands-on learning and work. Self-driven individual with problem solving and time management skills. Well-organized team player with strong communication abilities.

## Currently

Full-time student at Brigham Young University - Idaho, studying Software Engineering with a minor in Data Science.

## Education

`Apr 2018 - Dec 2018`
__Utah State University, Logan UT__

`Apr 2021 - now`
__Brigham Young University-Idaho, Cambridge__
3.76 GPA, B.S. in Software Engineering, Minor in Data Science

## Projects

### GITHUB.COM/DREWJHOWELLS

- __Android Agenda App & Task Manager App;__ productivity apps using JetPack Compose UI.
- __Typescript Forecast Console App;__ given a location, returns forecast from OpenWeatherAPI.
- __C++ Kaizo Platformer Game;__ used Raylib graphics, I/O, physics engine, and custom animation.
- __Crash Courses/Workshops;__ developed templates to teach programming concepts to students.


## Occupation

`Apr 2024- now`
__Teaching Assistant, BYU-I CSE Department__
- Graded student work and left individual feedback for over 75 students.
- Developed python scripts to automatically grade assignments.

`Mar 2024- Aug 2024`
__Founder & President, BYU-I Computing Society Mobile Development Team__
- Organized over a dozen students into teams to work on various mobile app projects.
- Invited several guest speakers to come and present on topics such as VSC, Ux Design, etc.
- Coordinated with society leadership and local businesses to create project opportunities.

`Jan 2022- Dec 2023`
__Missionary, The Church of Jesus Christ of Latter-day Saints__
- Trained and taught hundreds of missionaries and community members on gospel principles.
- Communicated and resolved conflicts with dozens of other missionaries.
- Managed and coordinated schedules with dozens of individuals daily.

`Jun 2019 - Apr 2021`
__Store Manager, Chick-fil-A Southlands__
- Managed a team of 100+ employees through communication and leadership skills.
- Trained 7 other leaders in finance skills, customer service and management strategies.

`Jan 2019 - Apr 2019`
__Intern, Spectrum Engineering MEP Firm__
- Designed engineering solutions using various engineering tools, software, and techniques.
- Collaborated weekly in a team environment & worked independently.

## Awards

`2014`
Apple Certified Mac Technician

`2016`
Eagle Scout

`2017`
AP Scholar with Honor

## Skills

- Python, Kotlin, C++, C#, SQL, HTML, CSS, R
- Git, GitHub, AWS
- Data Visualization, Web Development, Mobile Development
- Self-Discipline, Time Management, Problem Solving, Communication & Interpersonal Skills
- Professional Spanish


<!-- ### Footer

Last updated: Oct 2024 -->